name: FastAPI Workflow

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: ["main"]
  
env:
  SECRET_KEY: test
  ALLOWED_HOSTS: localhost 127.0.0.1
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
        
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ./venv
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

    - name: Set up Python
      uses: actions/setup-python@v5.0.0
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Ruff Linter
      run: |
        pip install ruff
      
    - name: Run Ruff Linter
      run: ruff check .
      
    - name: Run Ruff Formatter
      run: ruff format --check
      
    # - name: Run tests
    #   run: |
    #     python -m pytest tests/
